# Generated by Django 5.0.3 on 2024-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.BooleanField(default=True),
        ),
    ]
